### ISSUE TITLE
Fix chat edit function

### ISSUE THREAD

**Issue by MaykeKerssens** [curio-team/github-classroom-lock#7]
Currently, when a student edits their sent chat message, and clicks on 'opslaan', nothing happens

**Comment by luttje** [comment]
Fixed.

Because it removes all chats after what you edit, I ask the user to confirm:

![afbeelding](https://github.com/curio-team/github-classroom-lock/assets/2738114/7cef44b5-cad8-4582-9971-fe96dac46902)
